In [1]:
import pandas as pd, numpy as np

import pymysql
import sqlalchemy
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

In [2]:
## connection setup
password = quote_plus("mysql123")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/black_friday_analysis"
)

In [3]:
df = pd.read_sql(
    "SELECT * FROM black_friday_data",
    engine
)

print("Data Inserted row count in mysql table",len(df))

Data Inserted row count in mysql table 550068

In [4]:
df.shape
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [5]:
missing_values = df.isnull().sum()

missing_values

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [6]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing_summary = missing_summary[
    missing_summary["Missing_Count"] > 0
]

missing_summary

                    Missing_Count  Missing_Percentage
Product_Category_2         173638           31.566643
Product_Category_3         383247           69.672659

In [7]:
duplicate_count = df.duplicated(
    subset=["User_ID", "Product_ID"]
).sum()

print("Duplicate transactions:", duplicate_count)

Duplicate transactions: 0

In [8]:
key_columns = ["User_ID", "Product_ID", "Purchase"]

key_validation = pd.DataFrame({
    "Missing_Count": df[key_columns].isnull().sum(),
    "Missing_Percentage": df[key_columns].isnull().mean() * 100
})

key_validation

            Missing_Count  Missing_Percentage
User_ID                 0                 0.0
Product_ID              0                 0.0
Purchase                0                 0.0

In [9]:
df["Purchase"].describe()

count    550068.000000
mean       9263.968713
std        5023.065394
min          12.000000
25%        5823.000000
50%        8047.000000
75%       12054.000000
max       23961.000000
Name: Purchase, dtype: float64

In [10]:
invalid_purchase = df[df["Purchase"] <= 0]

print("Invalid purchase records:", len(invalid_purchase))

Invalid purchase records: 0

In [12]:
df["Gender"].unique()

array(['F', 'M'], dtype=object)

In [13]:
df["Age"].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [14]:
df["City_Category"].unique()

array(['A', 'C', 'B'], dtype=object)

In [15]:
df["Stay_In_Current_City_Years"].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [16]:
## Create a Python Validation Summary
validation_summary = {
    "Total Transactions": len(df),
    "Total Columns": len(df.columns),
    "Distinct Customers": df["User_ID"].nunique(),
    "Distinct Products": df["Product_ID"].nunique(),
    "Missing User_ID": df["User_ID"].isnull().sum(),
    "Missing Product_ID": df["Product_ID"].isnull().sum(),
    "Missing Purchase": df["Purchase"].isnull().sum(),
    "Missing Product_Category_2": df["Product_Category_2"].isnull().sum(),
    "Missing Product_Category_3": df["Product_Category_3"].isnull().sum(),
    "Duplicate Transactions": df.duplicated(
        subset=["User_ID", "Product_ID"]
    ).sum(),
    "Invalid Purchase Values": (df["Purchase"] <= 0).sum()
}

validation_summary

{'Total Transactions': 550068,
 'Total Columns': 12,
 'Distinct Customers': 5891,
 'Distinct Products': 3631,
 'Missing User_ID': np.int64(0),
 'Missing Product_ID': np.int64(0),
 'Missing Purchase': np.int64(0),
 'Missing Product_Category_2': np.int64(173638),
 'Missing Product_Category_3': np.int64(383247),
 'Duplicate Transactions': np.int64(0),
 'Invalid Purchase Values': np.int64(0)}

In [17]:
validation_df = pd.DataFrame(
    validation_summary.items(),
    columns=["Validation Metric", "Result"]
)

validation_df

             Validation Metric  Result
0           Total Transactions  550068
1                Total Columns      12
2           Distinct Customers    5891
3            Distinct Products    3631
4              Missing User_ID       0
5           Missing Product_ID       0
6             Missing Purchase       0
7   Missing Product_Category_2  173638
8   Missing Product_Category_3  383247
9       Duplicate Transactions       0
10     Invalid Purchase Values       0

In [18]:
validation_df.to_excel(
    "Black_Friday_Python_Validation_Report.xlsx",
    index=False
)